### ISSUE TITLE
getArticles and getWeather are inconsistent

### ISSUE THREAD

**Issue by shiryz** [fac-u/take-me-away#55] opened 2016-11-23 17:01 UTC
getArticles required from news.js while getWeather is implemented in server.js.

**Comment by stevehopkinson** [comment] 2016-11-23 17:13
Yup! We got halfway through making it modular, but not quite as far as moving getWeather into its own file…

**Comment by jsms90** [comment] 2016-11-23 17:40
duplicate of #27

**Closed as completed by jsms90** 2016-11-23 17:40 UTC
